### ISSUE TITLE
Cannot add clients when guest

### ISSUE THREAD

**Issue by radumg** [speckleworks/SpeckleViewer#29]
## Steps to reproduce
- Navigate to the viewer app : https://s003.speckle.works/view/?Hk8lgC8W-,BJqlzkPZb
- select Continue as Guest`

### Add button missing
- [ ] We should now see the `+` or `Add` button to add a stream.

Not sure if this is disabled because of `Guest` status. If it is, we should update the message accordingly.

![speckle viewer](https://user-images.githubusercontent.com/11439624/38083690-3f0c2d5a-3342-11e8-8eeb-ad629f0297c2.PNG)

### bonus issue : streams not loading
- [ ] None of the [streams from the docs](https://github.com/speckleworks/speckleworks-website/issues/5) seem to load, but this may be because they've been deleted on the server ?

![streams not loading](https://user-images.githubusercontent.com/11439624/38083800-94dbd7bc-3342-11e8-9137-0ac16fed1cd7.PNG)

**Comment by didimitrie** [comment]
the s003 viewer that is deployed on  the server is literally ancient. @mswaidan has made big on the viewer, we're going to deploy them soon...
