### ISSUE TITLE
View clipping

### ISSUE THREAD

**Issue by dongyeop-lee** [speckleworks/SpeckleViewer#4]
![image](https://user-images.githubusercontent.com/29285657/31856097-2e28e736-b687-11e7-840e-b0c67a664c74.png)
The viewer clips the model as seen in this image. I'm not sure what the issue is.

Dongyeop

**Comment by teocomi** [comment]
Also getting view clipping upon zooping on this stream: https://hestia.speckle.works/view/?streams=SyVi-Vft7
Attached a gif if you can't replicate.

![speckle-view-issue](https://user-images.githubusercontent.com/2679513/46085709-87ac2700-c19e-11e8-85d8-cef23dace321.gif)

**Comment by alvpickmans** [comment]
most likely Three.js camera's near/far settings (happens with large models on threejs [editor](https://threejs.org/editor/) as well)

**Comment by nicoazel** [comment]
Speckle Viewer exposes the three scene object so you can modify camera values in the browser console:
open developer panel > console > and type:

`scene.children[1].far =  "your desired setting"
`

[Three JS Camera Documentation](https://threejs.org/docs/index.html#api/en/cameras/PerspectiveCamera)

**Comment by didimitrie** [comment]
That’s a nice hack! Pity we can’t make it standard practice! 

The problem’s a bit more complicated, afaik:  
to correctly set the `camera.far` we need to wait for the stream to load, calculate the bounding box, and adjust accordingly. This will also need to be done most probably on every change (stream add/remove/refresh) or something.

**Comment by alvpickmans** [comment]
We could also add a textbox/slider to modify them manually and cache the values on the browser.

**Comment by mswaidan** [comment]
pr #72 should fix this. Please reopen if you're able to recreate again.

**Comment by didimitrie** [comment]
I'm opening it again as the recompute is  happening way to often and causing stutter. I'm getting `[Violation] 'mousemove' handler took 306ms` on my machine. 

Currently it's  happening on any control move, which is too often (see https://github.com/speckleworks/SpeckleViewer/blob/master/src/components/SpeckleRenderer.vue#L356) 

I think it should happen only on `endLoad` of a stream. I'll have a looksie in it!

**Comment by mswaidan** [comment]
Ah okay. It worked smoothly on my browser but maybe my scene was too simple to cause it to bog down. 

I initially only had `setFar` run when the stream finished loading or zoomExtents was called, but if you "zoom out," the camera.far plane is no longer deep enough to capture whole scene, so clipping comes back. So thought was call it whenever the camera moves too. But maybe we just add a bit of extra depth to setFar to deal with a little zooming out, and accept that when you zoom out too far the scene will clip.

**Comment by mswaidan** [comment]
@didimitrie can you take https://github.com/speckleworks/SpeckleViewer/tree/matt/clipping for a spin? Runs smoothly for me but would like to test against your stream before opening PR

Logic:
On mount, run `computeSceneBoundingSphere()` to get & store `this.sceneBoundingSphere`
On scene update, do the same.
`zoomExtents` & `setFar` use the stored `this.sceneBoundingSphere`

I'm still calling `setFar` on camera move, but it's a pretty low cost operation and isn't causing issues for me.

**Comment by didimitrie** [comment]
Will do later today, sorry for the delay...

**Comment by didimitrie** [comment]
more than one year later... closed in #78
