### ISSUE TITLE
One-click jumping to SpeckleViewer / Online Interface from node

### ISSUE THREAD

**Issue by Eckart-S** [speckleworks/SpeckleViewer#40]
It should be possible to easily and directly jump from a node to the web with a mouse click only, e.g.

- to the administration view that shows all streams for a user
- to a project view that shows all project streams
- to a 3D & json view for one specific streams (this stream is directly shown)
- to a 3D & json view for multiple streams merged together (this streams are directly shown)
- to a 3D & json view for a specific layer or multiple layers of a stream (this 3D is directly shown)
- etc.

A login should NOT be necessary - can the APIToken be used for a cloud server authorization and sent in the header or similar workflow to do this?

I am not sure the above is possible currently?
If yes, can someone please list the URLs and URL parameters to use for this?

**Comment by didimitrie** [comment]
this dropped under the radar for a while, didn't it? 

For 3d or 3d merged: `[SERVER_URL]/view?streams=StreamId1,StreamId2,StreamIdN` - you can add more streams in the query param. 

For data view `[SERVER_URL]/api/v1/streams/StreamId` and `[SERVER_URL]/api/v1/streams/StreamId/objects` for objects. You can append query params, like `?fields=layers,baseProperties` to select what fields you get. Multiple streams won't work at the same time won't work. 

For admin, this right now is `[SERVER_URL]/admin` or just `[SERVER_URL]`. There's a plugin system in the pipeline for the server which is based on [a plugin config file](https://github.com/speckleworks/SpeckleViewer/blob/master/speckle-plugin-manifest.json) which may allow to register external commands, but that gets slightly complicated now.

I won't risk sending login tokens in the url, but if the user previously logged in he should be able to reuse the token stored in localstorage, until it expires.
