### ISSUE TITLE
Should we store viewer state in localStorage?

### ISSUE THREAD

**Issue by mswaidan** [speckleworks/SpeckleViewer#47]
I'm working on a UI component that lets the user store some settings for the viewer. They're set in the Vuex store so we can grab them to use various components. I'm setting them also in localStorage so that on a browser refresh, a user's settings persist.

A few questions:

1. Should the viewerSettings object be attached the the user object on the server, so that I can keep my settings between browsers? Seems like maybe overkill / more work for @didimitrie  Or, is there some better way to store these?

2. Should other pieces of the state: which streams are loaded, etc., be cached in localStorage so that on a browser refresh, user doesn't have to go back and add all their streams again?

What do people think?

**Comment by didimitrie** [comment]
streamIds are now stored in url, viewer settings are serialised as before in localStorage. I'll close this baby!
