### ISSUE TITLE
Move non runtime dependencies to devDependencies

### ISSUE THREAD

**Issue by mswaidan** [speckleworks/SpeckleViewer#59]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
We don't pull a big bloated set of dependencies on `npm install @speckle/speckle-viewer`

#### Actual Behaviour
We install everything but the kitchen sink

#### Proposed Solution (if any)
Move non runtime dependencies to devDependencies

**Comment by didimitrie** [comment]
closed in #78
