### ISSUE TITLE
Overhaul Viewer Completely

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleViewer#6]
The viewer needs a complete overhaul, ui-wise and functionality wise. 

Key features:
- filter functionality and querying 
- better login flow
- comments & saved views
- metadata display of objects, etc. 
- display single objects too, not just streams

Optional nice haves: 
- Integrate defintion controller functionality
- Screenshots & link sharing functionality 
- Tabular view

...

**Comment by didimitrie** [comment]
This is actively in progress, so let's close it for now as it's not useful 🖖?

**Comment by mswaidan** [comment]
Yes, can refer back to it as needed
